##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.bash:5.0.18 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "bash"
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="bash" \
    CONTECO_NAME="api" \
    CONTECO_TAG="5.0.18" \
    CONTECO_BASE="external.bash:5.0.18" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="bash" \
      io.vcweb.name="api" \
      io.vcweb.tag="5.0.18" \
      io.vcweb.base="external.bash:5.0.18" \
      io.vcweb.build="image-base" \
      io.vcweb.label="bash.api - Conteco" \
      io.vcweb.description="ContEco Bash base image for API implementation." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.bash.api --help"
##### END image.base/Dockerfile/env-labels-footer #####
